version: "3.8"

services:
  web_app:
    container_name: ${PROJECT_SLUG}_web
    build:
      context: .
      dockerfile: backend.dockerfile

    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: ${PROJECT_SLUG}_db
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    env_file:
      - .env
